name: Testing one page with GitHub Actions + Lighthouse CI
on: [push]
jobs:
  lhci:
    name: lighthouse-ci
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v1
      - name: NodeJS 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          yarn
          npm run build
      - name:
        run: |
          npm install -g @lhci/cli@v0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI Failed!!!!"